name: local_storage_cache_ios
description: iOS implementation of the local_storage_cache plugin.
version: 2.0.0
homepage: https://github.com/mathtechstudio/local-storage-cache

resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_storage_cache_platform_interface:
    path: ../local_storage_cache_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    implements: local_storage_cache
    platforms:
      ios:
        pluginClass: LocalStorageCacheIosPlugin
