name: local_storage_cache_web
description: Web implementation of the local_storage_cache plugin.
version: 2.0.0
homepage: https://github.com/mathtechstudio/local-storage-cache

resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  local_storage_cache_platform_interface: ^2.0.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    implements: local_storage_cache
    platforms:
      web:
        pluginClass: LocalStorageCacheWeb
        fileName: local_storage_cache_web.dart
