name: local_storage_cache
description: A comprehensive Flutter package for managing local storage and caching with advanced features like encryption, TTL, multi-space architecture, and more.
version: 2.0.0
publish_to: none
homepage: https://github.com/protheeuz/local-storage-cache
repository: https://github.com/protheeuz/local-storage-cache

resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  local_storage_cache_platform_interface:
    path: ../local_storage_cache_platform_interface
  path: ^1.9.0
  path_provider: ^2.1.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: local_storage_cache_android
      ios:
        default_package: local_storage_cache_ios
      macos:
        default_package: local_storage_cache_macos
      windows:
        default_package: local_storage_cache_windows
      linux:
        default_package: local_storage_cache_linux
      web:
        default_package: local_storage_cache_web
