name: local_storage_cache_platform_interface
description: A common platform interface for the local_storage_cache plugin.
version: 2.0.0
homepage: https://github.com/protheeuz/local-storage-cache

resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^6.0.0
